# Site settings
title: lab34's CV 
description: Just a test
favicon: /assets/img/avatar.JPG
baseurl: https://ddbullfrog.github.io/resumecard
url: https://ddbullfrog.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: lab34
  title: IT Guy since 1989
  address: France
  email: me@somwhere.com
  link: 
  weibo:
  github: lab34
  linkedin: 
  twitter: 
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: A big company
      location: France
      title: IT Guy
      started: 1989
      duration: (1989 - Present)
      description: I've occupied several jobs, just an IT guy, a developper, a project manager, a project director, a product owner, but at the end, I'm still the IT Guy.
    - work2:
      company: Home
      location: France
      title: IT lover
      started: 1984
      duration: (1984 - Present)
      description: IT enthusiast
  educationHistory:
    - education1:
      organization: University
      location: France
      degree: 1st Year
      major: Sciences
      started: 1986
      duration: (1986 - 1988)
      description: not good in class
  languages:
    - language1:
      name: French
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Spanish
      proficiency: Not good at all
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: C
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: Java
      percentage: 70%
    - skill5:
      name: Bash
      percentage: 90%
